//go:build amd64

package xxhash

import "golang.org/x/sys/cpu"

// accumStripeAVX2 and accumStripeSSE2 fold one 64-byte stripe into the eight
// lanes of acc. accumRunAVX2 and accumRunSSE2 fold nStripes consecutive stripes
// in a single call, keeping the accumulator lanes resident in vector registers
// across the run (the secret advances by 8 bytes per stripe). Generated by
// go-asmgen (accum_amd64_gen.go) into accum_amd64.s.
func accumStripeAVX2(acc *[8]uint64, p, sec []byte)
func accumStripeSSE2(acc *[8]uint64, p, sec []byte)
func accumRunAVX2(acc *[8]uint64, p, sec []byte, nStripes int)
func accumRunSSE2(acc *[8]uint64, p, sec []byte, nStripes int)

var hasAVX2 = cpu.X86.HasAVX2

func accumStripe(acc *[8]uint64, p, sec []byte) {
	if hasAVX2 {
		accumStripeAVX2(acc, p, sec)
		return
	}
	accumStripeSSE2(acc, p, sec)
}

// accumRun folds nStripes consecutive stripes starting at p, with the secret
// advancing by 8 bytes per stripe (the secret[s*8:] schedule), keeping the
// accumulator resident in vector registers for the whole run. nStripes must be
// >= 1.
func accumRun(acc *[8]uint64, p, sec []byte, nStripes int) {
	if hasAVX2 {
		accumRunAVX2(acc, p, sec, nStripes)
		return
	}
	accumRunSSE2(acc, p, sec, nStripes)
}
