//go:build amd64

package xxhash

import "golang.org/x/sys/cpu"

// accumStripeAVX2 and accumStripeSSE2 fold one 64-byte stripe into the eight
// lanes of acc. Generated by go-asmgen (accum_amd64_gen.go) into accum_amd64.s.
func accumStripeAVX2(acc *[8]uint64, p, sec []byte)
func accumStripeSSE2(acc *[8]uint64, p, sec []byte)

var hasAVX2 = cpu.X86.HasAVX2

func accumStripe(acc *[8]uint64, p, sec []byte) {
	if hasAVX2 {
		accumStripeAVX2(acc, p, sec)
		return
	}
	accumStripeSSE2(acc, p, sec)
}
