//go:build s390x

package xxhash

// accumStripeVEC folds one 64-byte stripe into the eight lanes of acc using the
// z/Architecture vector facility (baseline on z13+, so no runtime dispatch).
// Generated by go-asmgen (accum_s390x_gen.go) into accum_s390x.s.
func accumStripeVEC(acc *[8]uint64, p, sec []byte)

func accumStripe(acc *[8]uint64, p, sec []byte) {
	accumStripeVEC(acc, p, sec)
}
