//go:build riscv64

package xxhash

import "golang.org/x/sys/cpu"

// accumStripeRVV folds one 64-byte stripe into the eight lanes of acc using the
// RISC-V Vector extension. Generated by go-asmgen (accum_riscv64_gen.go) into
// accum_riscv64.s.
func accumStripeRVV(acc *[8]uint64, p, sec []byte)

var hasRVV = cpu.RISCV64.HasV

func accumStripe(acc *[8]uint64, p, sec []byte) {
	if hasRVV {
		accumStripeRVV(acc, p, sec)
		return
	}
	accumStripeScalar(acc, p, sec)
}
