//go:build ppc64le

package xxhash

// accumStripeVSX folds one 64-byte stripe into the eight lanes of acc using VSX.
// accumRunVSX folds nStripes consecutive stripes in a single call, keeping the
// accumulator pairs resident in vector registers across the run (the secret
// advances by 8 bytes per stripe). accumScrambleVSX folds nBlocks complete
// 1024-byte blocks (16 stripes + the inter-block scramble each) in a single
// call, keeping the accumulator resident across the WHOLE run and running the
// scramble in-register. VSX is baseline on POWER8+ and the kernel uses only
// baseline VSX ops (no ISA-3.0), so there is no runtime feature dispatch and it
// runs on POWER8 as well as POWER9. Generated by go-asmgen (accum_ppc64le_gen.go)
// into accum_ppc64le.s.
func accumStripeVSX(acc *[8]uint64, p, sec []byte)
func accumRunVSX(acc *[8]uint64, p, sec []byte, nStripes int)
func accumScrambleVSX(acc *[8]uint64, p, sec []byte, nBlocks int)

func accumStripe(acc *[8]uint64, p, sec []byte) {
	accumStripeVSX(acc, p, sec)
}

// accumRun folds nStripes consecutive stripes starting at p, advancing the
// secret by 8 bytes per stripe, with the accumulator resident in vector
// registers for the whole run. nStripes must be >= 1.
func accumRun(acc *[8]uint64, p, sec []byte, nStripes int) {
	accumRunVSX(acc, p, sec, nStripes)
}

// accumScramble folds nBlocks complete 1024-byte blocks (16 stripes + scramble
// each) in a single asm call, with the accumulator resident in vector registers
// for the whole run. nBlocks must be >= 1.
func accumScramble(acc *[8]uint64, p, sec []byte, nBlocks int) {
	accumScrambleVSX(acc, p, sec, nBlocks)
}
