//go:build loong64

package xxhash

import "golang.org/x/sys/cpu"

// accumStripeLSX folds one 64-byte stripe into the eight lanes of acc using the
// LoongArch SIMD eXtension. Generated by go-asmgen (accum_loong64_gen.go) into
// accum_loong64.s.
func accumStripeLSX(acc *[8]uint64, p, sec []byte)

var hasLSX = cpu.Loong64.HasLSX

func accumStripe(acc *[8]uint64, p, sec []byte) {
	if hasLSX {
		accumStripeLSX(acc, p, sec)
		return
	}
	accumStripeScalar(acc, p, sec)
}
