// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·accumStripeVEC(SB), NOSPLIT, $0-56
	MOVD acc+0(FP), R1
	MOVD p_base+8(FP), R2
	MOVD sec_base+32(FP), R3
	MOVD $revsel<>(SB), R5
	VL (R5), V31
	VL 0(R2), V0
	VL 0(R3), V1
	VPERM V0, V0, V31, V0
	VPERM V1, V1, V31, V1
	VX V0, V1, V2
	VESRLG $32, V2, V4
	VESLG $32, V2, V3
	VESRLG $32, V3, V3
	VMLOF V3, V4, V5
	VPDI $4, V0, V0, V6
	VL 0(R1), V7
	VAG V7, V5, V7
	VAG V7, V6, V7
	VST V7, 0(R1)
	VL 16(R2), V0
	VL 16(R3), V1
	VPERM V0, V0, V31, V0
	VPERM V1, V1, V31, V1
	VX V0, V1, V2
	VESRLG $32, V2, V4
	VESLG $32, V2, V3
	VESRLG $32, V3, V3
	VMLOF V3, V4, V5
	VPDI $4, V0, V0, V6
	VL 16(R1), V7
	VAG V7, V5, V7
	VAG V7, V6, V7
	VST V7, 16(R1)
	VL 32(R2), V0
	VL 32(R3), V1
	VPERM V0, V0, V31, V0
	VPERM V1, V1, V31, V1
	VX V0, V1, V2
	VESRLG $32, V2, V4
	VESLG $32, V2, V3
	VESRLG $32, V3, V3
	VMLOF V3, V4, V5
	VPDI $4, V0, V0, V6
	VL 32(R1), V7
	VAG V7, V5, V7
	VAG V7, V6, V7
	VST V7, 32(R1)
	VL 48(R2), V0
	VL 48(R3), V1
	VPERM V0, V0, V31, V0
	VPERM V1, V1, V31, V1
	VX V0, V1, V2
	VESRLG $32, V2, V4
	VESLG $32, V2, V3
	VESRLG $32, V3, V3
	VMLOF V3, V4, V5
	VPDI $4, V0, V0, V6
	VL 48(R1), V7
	VAG V7, V5, V7
	VAG V7, V6, V7
	VST V7, 48(R1)
	RET


GLOBL revsel<>(SB), RODATA|NOPTR, $16
DATA revsel<>+0(SB)/1, $7
DATA revsel<>+1(SB)/1, $6
DATA revsel<>+2(SB)/1, $5
DATA revsel<>+3(SB)/1, $4
DATA revsel<>+4(SB)/1, $3
DATA revsel<>+5(SB)/1, $2
DATA revsel<>+6(SB)/1, $1
DATA revsel<>+7(SB)/1, $0
DATA revsel<>+8(SB)/1, $15
DATA revsel<>+9(SB)/1, $14
DATA revsel<>+10(SB)/1, $13
DATA revsel<>+11(SB)/1, $12
DATA revsel<>+12(SB)/1, $11
DATA revsel<>+13(SB)/1, $10
DATA revsel<>+14(SB)/1, $9
DATA revsel<>+15(SB)/1, $8
