//go:build loong64

package xxhash

import "golang.org/x/sys/cpu"

// accumStripeLSX folds one 64-byte stripe into the eight lanes of acc using the
// LoongArch SIMD eXtension. accumRunLSX folds nStripes consecutive stripes in a
// single call, keeping the accumulator pairs resident in vector registers across
// the run (the secret advances by 8 bytes per stripe). accumScrambleLSX folds
// nBlocks complete 1024-byte blocks (16 stripes + the inter-block scramble each)
// in a single call, keeping the accumulator resident across the WHOLE run and
// running the scramble in-register. Generated by go-asmgen (accum_loong64_gen.go)
// into accum_loong64.s.
func accumStripeLSX(acc *[8]uint64, p, sec []byte)
func accumRunLSX(acc *[8]uint64, p, sec []byte, nStripes int)
func accumScrambleLSX(acc *[8]uint64, p, sec []byte, nBlocks int)

var hasLSX = cpu.Loong64.HasLSX

func accumStripe(acc *[8]uint64, p, sec []byte) {
	if hasLSX {
		accumStripeLSX(acc, p, sec)
		return
	}
	accumStripeScalar(acc, p, sec)
}

// accumRun folds nStripes consecutive stripes starting at p, advancing the
// secret by 8 bytes per stripe, with the accumulator resident in vector
// registers for the whole run. nStripes must be >= 1.
func accumRun(acc *[8]uint64, p, sec []byte, nStripes int) {
	if hasLSX {
		accumRunLSX(acc, p, sec, nStripes)
		return
	}
	for s := 0; s < nStripes; s++ {
		accumStripeScalar(acc, p[s*stripeBytes:], sec[s*8:])
	}
}

// accumScramble folds nBlocks complete 1024-byte blocks (16 stripes + scramble
// each) in a single asm call, with the accumulator resident in vector registers
// for the whole run. nBlocks must be >= 1.
func accumScramble(acc *[8]uint64, p, sec []byte, nBlocks int) {
	if hasLSX {
		accumScrambleLSX(acc, p, sec, nBlocks)
		return
	}
	for i := 0; i < nBlocks; i++ {
		blk := p[i*blockBytes:]
		for s := 0; s < blockStripes; s++ {
			accumStripeScalar(acc, blk[s*stripeBytes:], sec[s*8:])
		}
		scramble(acc)
	}
}
