//go:build arm64

package xxhash

// accumStripeNEON folds one 64-byte stripe into the eight lanes of acc. NEON is
// baseline on arm64, so there is no runtime feature dispatch. Generated by
// go-asmgen (accum_arm64_gen.go) into accum_arm64.s.
func accumStripeNEON(acc *[8]uint64, p, sec []byte)

func accumStripe(acc *[8]uint64, p, sec []byte) {
	accumStripeNEON(acc, p, sec)
}
