//go:build arm64

package xxhash

// accumStripeNEON folds one 64-byte stripe into the eight lanes of acc.
// accumRunNEON folds nStripes consecutive stripes in a single call, keeping the
// accumulator lanes resident in vector registers across the run (the secret
// advances by 8 bytes per stripe). accumScrambleNEON folds nBlocks complete
// 1024-byte blocks (16 stripes + the inter-block scramble each) in a single
// call, keeping the accumulator resident across the WHOLE multi-block run and
// running the scramble in-register. NEON is baseline on arm64, so there is no
// runtime feature dispatch. Generated by go-asmgen (accum_arm64_gen.go) into
// accum_arm64.s.
func accumStripeNEON(acc *[8]uint64, p, sec []byte)
func accumRunNEON(acc *[8]uint64, p, sec []byte, nStripes int)
func accumScrambleNEON(acc *[8]uint64, p, sec []byte, nBlocks int)

func accumStripe(acc *[8]uint64, p, sec []byte) {
	accumStripeNEON(acc, p, sec)
}

// accumRun folds nStripes consecutive stripes starting at p, advancing the
// secret by 8 bytes per stripe, with the accumulator resident in vector
// registers for the whole run. nStripes must be >= 1.
func accumRun(acc *[8]uint64, p, sec []byte, nStripes int) {
	accumRunNEON(acc, p, sec, nStripes)
}

// accumScramble folds nBlocks complete 1024-byte blocks (16 stripes + scramble
// each) in a single asm call, with the accumulator resident in vector registers
// for the whole run. nBlocks must be >= 1.
func accumScramble(acc *[8]uint64, p, sec []byte, nBlocks int) {
	accumScrambleNEON(acc, p, sec, nBlocks)
}
