//go:build s390x

package xxhash

// accumStripeVEC folds one 64-byte stripe into the eight lanes of acc using the
// z/Architecture vector facility. accumRunVEC folds nStripes consecutive stripes
// in a single call, keeping the accumulator pairs resident in vector registers
// across the run (the secret advances by 8 bytes per stripe). accumScrambleVEC
// folds nBlocks complete 1024-byte blocks (16 stripes + the inter-block scramble
// each) in a single call, keeping the accumulator resident across the WHOLE run
// and running the scramble in-register. The vector facility is baseline on z13+,
// so there is no runtime dispatch. Generated by go-asmgen (accum_s390x_gen.go)
// into accum_s390x.s.
func accumStripeVEC(acc *[8]uint64, p, sec []byte)
func accumRunVEC(acc *[8]uint64, p, sec []byte, nStripes int)
func accumScrambleVEC(acc *[8]uint64, p, sec []byte, nBlocks int)

func accumStripe(acc *[8]uint64, p, sec []byte) {
	accumStripeVEC(acc, p, sec)
}

// accumRun folds nStripes consecutive stripes starting at p, advancing the
// secret by 8 bytes per stripe, with the accumulator resident in vector
// registers for the whole run. nStripes must be >= 1.
func accumRun(acc *[8]uint64, p, sec []byte, nStripes int) {
	accumRunVEC(acc, p, sec, nStripes)
}

// accumScramble folds nBlocks complete 1024-byte blocks (16 stripes + scramble
// each) in a single asm call, with the accumulator resident in vector registers
// for the whole run. nBlocks must be >= 1.
func accumScramble(acc *[8]uint64, p, sec []byte, nBlocks int) {
	accumScrambleVEC(acc, p, sec, nBlocks)
}
