// Package xxhash implements XXH3-64, the 64-bit variant of the XXH3 hash
// family, in pure Go with no cgo and no GOEXPERIMENT — on a plain `go build`.
//
// Digests are bit-exact with the canonical reference implementation
// (Cyan4973/xxHash) and with zeebo/xxh3 for the default (unseeded) secret. The
// hot 64-byte-stripe accumulator — eight independent uint64 lanes mixed with the
// secret by a 32x32->64 multiply-add — is SIMD assembly (generated by
// go-asmgen) on all six of Go's 64-bit SIMD targets. On amd64 the stripe loop is
// a multi-accumulator kernel: the four 256-bit accumulator banks stay resident
// in vector registers across a whole run of stripes (no per-stripe memory
// round-trip), matching the canonical XXH3 accumulate_512 structure that hides
// the multiply/add latency at scale. The targets:
//
//	amd64   AVX2 / SSE2
//	arm64   NEON
//	ppc64le VSX
//	s390x   vector facility (big-endian)
//	riscv64 RVV
//	loong64 LSX
//
// with a portable scalar fallback elsewhere. Input is always decoded
// little-endian (the XXH3 spec is little-endian), so the digest is identical on
// the big-endian s390x target.
//
// API:
//
//	Sum64(b []byte) uint64
//	Sum64String(s string) uint64
//	New() *Digest        // a streaming hash.Hash64
package xxhash

import (
	"encoding/binary"
	"math/bits"
)

// XXH3 primes.
const (
	prime32_1 = 0x9E3779B1
	prime32_2 = 0x85EBCA77
	prime32_3 = 0xC2B2AE3D

	prime64_1 = 0x9E3779B185EBCA87
	prime64_2 = 0xC2B2AE3D27D4EB4F
	prime64_3 = 0x165667B19E3779F9
	prime64_4 = 0x85EBCA77C2B2AE63
	prime64_5 = 0x27D4EB2F165667C5
)

const (
	stripeBytes  = 64  // one accumulation stripe: 8 lanes x 8 bytes
	secretBytes  = 192 // length of the default secret
	blockStripes = 16  // stripes per scramble block (1024 bytes)
	blockBytes   = stripeBytes * blockStripes
)

// secret is the canonical XXH3 default secret (kSecret in the reference).
var secret = [secretBytes]byte{
	0xb8, 0xfe, 0x6c, 0x39, 0x23, 0xa4, 0x4b, 0xbe, 0x7c, 0x01, 0x81, 0x2c, 0xf7, 0x21, 0xad, 0x1c,
	0xde, 0xd4, 0x6d, 0xe9, 0x83, 0x90, 0x97, 0xdb, 0x72, 0x40, 0xa4, 0xa4, 0xb7, 0xb3, 0x67, 0x1f,
	0xcb, 0x79, 0xe6, 0x4e, 0xcc, 0xc0, 0xe5, 0x78, 0x82, 0x5a, 0xd0, 0x7d, 0xcc, 0xff, 0x72, 0x21,
	0xb8, 0x08, 0x46, 0x74, 0xf7, 0x43, 0x24, 0x8e, 0xe0, 0x35, 0x90, 0xe6, 0x81, 0x3a, 0x26, 0x4c,
	0x3c, 0x28, 0x52, 0xbb, 0x91, 0xc3, 0x00, 0xcb, 0x88, 0xd0, 0x65, 0x8b, 0x1b, 0x53, 0x2e, 0xa3,
	0x71, 0x64, 0x48, 0x97, 0xa2, 0x0d, 0xf9, 0x4e, 0x38, 0x19, 0xef, 0x46, 0xa9, 0xde, 0xac, 0xd8,
	0xa8, 0xfa, 0x76, 0x3f, 0xe3, 0x9c, 0x34, 0x3f, 0xf9, 0xdc, 0xbb, 0xc7, 0xc7, 0x0b, 0x4f, 0x1d,
	0x8a, 0x51, 0xe0, 0x4b, 0xcd, 0xb4, 0x59, 0x31, 0xc8, 0x9f, 0x7e, 0xc9, 0xd9, 0x78, 0x73, 0x64,
	0xea, 0xc5, 0xac, 0x83, 0x34, 0xd3, 0xeb, 0xc3, 0xc5, 0x81, 0xa0, 0xff, 0xfa, 0x13, 0x63, 0xeb,
	0x17, 0x0d, 0xdd, 0x51, 0xb7, 0xf0, 0xda, 0x49, 0xd3, 0x16, 0x55, 0x26, 0x29, 0xd4, 0x68, 0x9e,
	0x2b, 0x16, 0xbe, 0x58, 0x7d, 0x47, 0xa1, 0xfc, 0x8f, 0xf8, 0xb8, 0xd1, 0x7a, 0xd0, 0x31, 0xce,
	0x45, 0xcb, 0x3a, 0x8f, 0x95, 0x16, 0x04, 0x28, 0xaf, 0xd7, 0xfb, 0xca, 0xbb, 0x4b, 0x40, 0x7e,
}

// initAcc is the XXH3 accumulator seed (the eight starting lane values).
var initAcc = [8]uint64{
	prime32_3, prime64_1, prime64_2, prime64_3,
	prime64_4, prime32_2, prime64_5, prime32_1,
}

// readU64 / readU32 decode little-endian regardless of host endianness, so the
// digest is identical on big-endian s390x.
func readU64(b []byte) uint64 { return binary.LittleEndian.Uint64(b) }
func readU32(b []byte) uint32 { return binary.LittleEndian.Uint32(b) }

func mulFold64(x, y uint64) uint64 {
	hi, lo := bits.Mul64(x, y)
	return hi ^ lo
}

func xxh3Avalanche(x uint64) uint64 {
	x ^= x >> 37
	x *= 0x165667919E3779F9
	x ^= x >> 32
	return x
}

func xxhAvalancheSmall(x uint64) uint64 {
	x ^= x >> 33
	x *= prime64_2
	x ^= x >> 29
	x *= prime64_3
	x ^= x >> 32
	return x
}

func rrmxmx(h, length uint64) uint64 {
	h ^= bits.RotateLeft64(h, 49) ^ bits.RotateLeft64(h, 24)
	h *= 0x9FB21C651E98DF25
	h ^= (h >> 35) + length
	h *= 0x9FB21C651E98DF25
	h ^= h >> 28
	return h
}

// Sum64 returns the XXH3-64 digest of b using the default secret.
func Sum64(b []byte) uint64 {
	l := len(b)
	switch {
	case l <= 16:
		return hashShort(b)
	case l <= 128:
		return hashMid(b)
	case l <= 240:
		return hashMidLong(b)
	default:
		return hashLong(b)
	}
}

// Sum64String returns the XXH3-64 digest of s using the default secret.
func Sum64String(s string) uint64 {
	return Sum64([]byte(s))
}

// hashShort handles 0..16 byte inputs.
func hashShort(b []byte) uint64 {
	l := len(b)
	switch {
	case l > 8: // 9..16
		inLo := readU64(b) ^ (readU64(secret[24:]) ^ readU64(secret[32:]))
		inHi := readU64(b[l-8:]) ^ (readU64(secret[40:]) ^ readU64(secret[48:]))
		folded := mulFold64(inLo, inHi)
		return xxh3Avalanche(uint64(l) + bits.ReverseBytes64(inLo) + inHi + folded)
	case l >= 4: // 4..8
		in1 := readU32(b)
		in2 := readU32(b[l-4:])
		in64 := uint64(in2) + uint64(in1)<<32
		keyed := in64 ^ (readU64(secret[8:]) ^ readU64(secret[16:]))
		return rrmxmx(keyed, uint64(l))
	case l > 0: // 1..3
		var acc uint64
		switch l {
		case 3:
			c12 := uint64(binary.LittleEndian.Uint16(b))
			c3 := uint64(b[2])
			acc = c12<<16 + c3 + 3<<8
		case 2:
			c12 := uint64(binary.LittleEndian.Uint16(b))
			acc = c12*(1<<24+1)>>8 + 2<<8
		default: // 1
			c1 := uint64(b[0])
			acc = c1*(1<<24+1<<16+1) + 1<<8
		}
		acc ^= uint64(readU32(secret[:]) ^ readU32(secret[4:]))
		// XXH64-style avalanche for the 1..3 byte combined value (the input is
		// already < 32 bits, so the usual leading x ^= x>>33 is a no-op and is
		// omitted, matching the reference).
		acc *= prime64_2
		acc ^= acc >> 29
		acc *= prime64_3
		acc ^= acc >> 32
		return acc
	default: // 0
		return xxhAvalancheSmall(readU64(secret[56:]) ^ readU64(secret[64:]))
	}
}

// hashMid handles 17..128 byte inputs.
func hashMid(b []byte) uint64 {
	l := len(b)
	acc := uint64(l) * prime64_1
	if l > 32 {
		if l > 64 {
			if l > 96 {
				acc += mulFold64(readU64(b[48:])^readU64(secret[96:]), readU64(b[56:])^readU64(secret[104:]))
				acc += mulFold64(readU64(b[l-64:])^readU64(secret[112:]), readU64(b[l-56:])^readU64(secret[120:]))
			}
			acc += mulFold64(readU64(b[32:])^readU64(secret[64:]), readU64(b[40:])^readU64(secret[72:]))
			acc += mulFold64(readU64(b[l-48:])^readU64(secret[80:]), readU64(b[l-40:])^readU64(secret[88:]))
		}
		acc += mulFold64(readU64(b[16:])^readU64(secret[32:]), readU64(b[24:])^readU64(secret[40:]))
		acc += mulFold64(readU64(b[l-32:])^readU64(secret[48:]), readU64(b[l-24:])^readU64(secret[56:]))
	}
	acc += mulFold64(readU64(b[0:])^readU64(secret[0:]), readU64(b[8:])^readU64(secret[8:]))
	acc += mulFold64(readU64(b[l-16:])^readU64(secret[16:]), readU64(b[l-8:])^readU64(secret[24:]))
	return xxh3Avalanche(acc)
}

// hashMidLong handles 129..240 byte inputs.
func hashMidLong(b []byte) uint64 {
	l := len(b)
	acc := uint64(l) * prime64_1
	for i := 0; i < 8; i++ {
		off := i * 16
		acc += mulFold64(readU64(b[off:])^readU64(secret[off:]), readU64(b[off+8:])^readU64(secret[off+8:]))
	}
	acc = xxh3Avalanche(acc)
	top := l &^ 15
	for i := 8 * 16; i < top; i += 16 {
		acc += mulFold64(readU64(b[i:])^readU64(secret[i-125:]), readU64(b[i+8:])^readU64(secret[i-117:]))
	}
	acc += mulFold64(readU64(b[l-16:])^readU64(secret[119:]), readU64(b[l-8:])^readU64(secret[127:]))
	return xxh3Avalanche(acc)
}

// hashLong handles inputs > 240 bytes: the full block/stripe accumulator.
func hashLong(b []byte) uint64 {
	acc := initAcc
	accumulate(&acc, b)

	out := uint64(len(b)) * prime64_1
	out += mulFold64(acc[0]^readU64(secret[11:]), acc[1]^readU64(secret[19:]))
	out += mulFold64(acc[2]^readU64(secret[27:]), acc[3]^readU64(secret[35:]))
	out += mulFold64(acc[4]^readU64(secret[43:]), acc[5]^readU64(secret[51:]))
	out += mulFold64(acc[6]^readU64(secret[59:]), acc[7]^readU64(secret[67:]))
	return xxh3Avalanche(out)
}

// accumulate runs the long-input pipeline over the whole input b (len > 240):
// full 1024-byte blocks (16 stripes each, then a scramble), the remaining whole
// stripes, and finally the last (possibly overlapping) stripe. accumStripe — the
// per-stripe 8-lane multiply-add — is the SIMD-accelerated kernel.
func accumulate(acc *[8]uint64, b []byte) {
	nBlocks := (len(b) - 1) / blockBytes
	for i := 0; i < nBlocks; i++ {
		blk := b[i*blockBytes:]
		// One full block is blockStripes stripes with the secret advancing by 8
		// bytes per stripe; accumRun keeps the accumulator lanes resident in
		// vector registers across the whole run (the multi-accumulator shape).
		accumRun(acc, blk, secret[:], blockStripes)
		scramble(acc)
	}
	// Process the remainder after the last full block.
	accumTail(acc, b, nBlocks*blockBytes)
}

// accumTail processes the bytes of b that follow the last full 1024-byte block
// (which starts at byte offset off): every whole stripe except the very last,
// then the final stripe aligned to the true end of b (reference XXH3 reads the
// last 64 bytes of the whole input, overlapping the previous block when the tail
// is not stripe-aligned), using the fixed secret offset 121. b[off:] must be
// 1..blockBytes long.
func accumTail(acc *[8]uint64, b []byte, off int) {
	rest := b[off:]
	nStripes := (len(rest) - 1) / stripeBytes
	if nStripes > 0 {
		accumRun(acc, rest, secret[:], nStripes)
	}
	// Last 64 bytes of the entire input (may reach back into the prior block).
	last := b[len(b)-stripeBytes:]
	accumStripe(acc, last, secret[secretBytes-stripeBytes-7:])
}

// scramble mixes the lanes between blocks.
func scramble(acc *[8]uint64) {
	for i := 0; i < 8; i++ {
		v := acc[i]
		v ^= v >> 47
		v ^= readU64(secret[secretBytes-stripeBytes+i*8:])
		v *= prime32_1
		acc[i] = v
	}
}

// accumStripeScalar is the portable per-stripe accumulator: for each of the 8
// lanes, XOR the 64-bit input word with the secret word, then add to the lane
// both the swapped input word and the 32x32->64 product of the low and high
// halves of the keyed value. This is the inner loop the SIMD kernels replace.
func accumStripeScalar(acc *[8]uint64, p, sec []byte) {
	for i := 0; i < 8; i++ {
		dv := readU64(p[i*8:])
		dk := dv ^ readU64(sec[i*8:])
		acc[i^1] += dv
		acc[i] += uint64(uint32(dk)) * (dk >> 32)
	}
}
